spring:
  application:
    name: spring_boot_3_demo

spring.cloud.vault:
  scheme: http
  enabled: true
  port: 8200
  fail-fast: true
  config:
    lifecycle:
      enabled: true
      min-renewal: 10s
      expiry-threshold: 1m
  authentication: TOKEN
  token: myroot

spring.config.import: vault://